# Generated by Django 4.2.7 on 2025-04-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="capacity",
        ),
    ]
